const fs = require("fs");
const path = require("path");
const PDFDocument = require("pdfkit");

/* ===========================
   UPLOAD VIDEO
   =========================== */
exports.uploadVideo = (req, res) => {
    if (!req.file) {
        return res.status(400).json({ msg: "No file uploaded" });
    }
    // File is already saved by multer middleware in /uploads
    // We simulate "processing" time and then trigger note generation logic

    const videoPath = req.file.path;

    // Simulate AI delay
    setTimeout(() => {
        // In a real app, we would send videoPath to an AI service here.
        console.log(`[AI Mock] Processed video: ${videoPath}`);
    }, 2000);

    res.json({
        msg: "Video uploaded successfully. AI processing started.",
        filename: req.file.filename
    });
};

/* ===========================
   GENERATE AI NOTES (MOCK)
   =========================== */
exports.generateNotes = (req, res) => {
    try {
        const { filename } = req.body;
        if (!filename) return res.status(400).json({ msg: "Filename required" });

        const notesFilename = `NOTES-${Date.now()}.pdf`;
        const notesPath = path.join(__dirname, "../uploads", notesFilename);

        const doc = new PDFDocument();
        doc.pipe(fs.createWriteStream(notesPath));

        // PDF Content
        // PDF Content
        doc.fontSize(24).font('Helvetica-Bold').text("SkillQuest AI Class Notes", { align: "center" });
        doc.moveDown(0.5);
        doc.fontSize(12).font('Helvetica').text(`Source Video: ${filename}`, { align: "center", color: 'grey' });
        doc.moveDown(2);

        // 1. Executive Summary
        doc.fontSize(16).font('Helvetica-Bold').text("1. Executive Summary");
        doc.moveDown(0.5);
        doc.fontSize(11).font('Helvetica').text("This session provided a comprehensive technical overview of the subject matter. The instructor introduced core principles, demonstrated practical applications using live coding examples, and addressed common pitfalls. The primary focus was on scalability and modular design patterns.");
        doc.moveDown(1.5);

        // 2. Key Concepts & Definitions
        doc.fontSize(16).font('Helvetica-Bold').text("2. Key Concepts & Definitions");
        doc.moveDown(0.5);

        const concepts = [
            { name: "Asynchronous Logic", desc: "Handling operations that occur independent of the main program flow." },
            { name: "Modular Architecture", desc: "Designing systems as independent, interchangeable modules." },
            { name: "Error Handling", desc: "Strategies for anticipating and resolving runtime errors gracefully." },
            { name: "API Integration", desc: "Connecting frontend interfaces with backend services." }
        ];

        concepts.forEach(c => {
            doc.font('Helvetica-Bold').text(`• ${c.name}: `, { continued: true });
            doc.font('Helvetica').text(c.desc);
            doc.moveDown(0.3);
        });
        doc.moveDown(1.5);

        // 3. Detailed Analysis
        doc.fontSize(16).font('Helvetica-Bold').text("3. Detailed Analysis");
        doc.moveDown(0.5);
        doc.font('Helvetica').text("The lecture began with a review of fundamental syntax before moving to complex state management. A significant portion of the time was dedicated to debugging techniques, specifically using browser developer tools and server-side logging. The instructor emphasized the importance of writing clean, self-documenting code to facilitate team collaboration.");
        doc.moveDown(1.5);

        // 4. External Resources (NEW)
        doc.fontSize(16).font('Helvetica-Bold').text("4. Recommended Resources");
        doc.moveDown(0.5);
        doc.fontSize(11).font('Helvetica').text("For further reading, please verify the following reliable sources:");
        doc.moveDown(0.5);

        // Links
        doc.fillColor('blue').text("• Wikipedia: Software Engineering", {
            link: "https://en.wikipedia.org/wiki/Software_engineering",
            underline: true
        });
        doc.moveDown(0.3);

        doc.text("• GeeksforGeeks: Computer Science Tutorials", {
            link: "https://www.geeksforgeeks.org/",
            underline: true
        });
        doc.moveDown(0.3);

        doc.text("• MDN Web Docs (Mozilla)", {
            link: "https://developer.mozilla.org/",
            underline: true
        });

        doc.fillColor('black'); // Reset
        doc.moveDown(2);

        doc.fontSize(10).text("Generated by SkillQuest AI Engine", { align: "center", color: "grey" });

        doc.end();

        // Return the public URL for the notes
        // Assuming 'uploads' is served statically from root
        const downloadUrl = `http://localhost:5000/uploads/${notesFilename}`;

        res.json({ downloadUrl });

    } catch (err) {
        console.error(err);
        res.status(500).json({ msg: "Note generation failed" });
    }
};
